### PR TITLE
Modification for M5Stick C Plus

### PR DESCRIPTION
**Pull request by JackyBurget**
I modify the program to works correctly with the M5Stick C Plus to use the max screen size.
I add new images for Left, Rigth and Thumbs.
I hope you will enjoy this.

### CODE REVIEW

**Comment by JackyBurget** [comment]
I modify the readme adding new picture.

**Comment by dominicklee** [comment]
Thank you for your efforts! I will review and merge the changes

**Comment by JackyBurget** [comment]
Was a pleasure.
I  just forgot to remove OmniLevel_3Dprint_leveler_modifie.ino folder (https://github.com/JackyBurget/3D-Print-Bed-Leveler/tree/main/OmniLevel_3Dprint_leveler_modifie.ino).
The important part is in 
https://github.com/JackyBurget/3D-Print-Bed-Leveler/tree/main/OmniLevel_3Dprint_leveler_C_and_Cplus.

All modification have been tested on M5Stic C and M5stickC Plus..

**Comment by JackyBurget** [comment]
i remove the folder
 [OmniLevel_3Dprint_leveler_modifie.ino](https://github.com/JackyBurget/3D-Print-Bed-Leveler/tree/main/OmniLevel_3Dprint_leveler_modifie.ino)

**Comment by dominicklee** [comment]
@JackyBurget Thanks for your contribution. I've merged your commits into the main branch. 

Looking forward to possibly working with you in future projects! All the best.

**Pull request merged**
